### ISSUE TITLE
Guide (Script)

### ISSUE THREAD

**Issue by ParkinT** [ParkinT/alcheme#21]
Collision with Guide produces a dialog box with text.

**Comment by fredcicles** [comment]
I've created a basic version.  If we detail out how we want it to work, more features can be added.

**Comment by fredcicles** [comment]
Added script MessageTypewriter.cs
Can assign an Image to be displayed as a background for the text.
Must assign a text object to display the text in.
Has some placeholders for plugging in sounds although they will not play at the moment.
Needs various enhancements as we determine what feature are desired.
